config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # qna's
  resources :qna_rooms
  post 'qna_questions/ask_question'
  get 'qna_questions/form'

  # polling's
  resources :pollings do
    collection do
      get 'user/status', to: 'user_polling#redirect_status_page', as: 'user_status'
      get 'user/:code', to: 'user_polling#form', as: 'user_polling'
      post 'user/submit', to: 'user_polling#submit', as: 'user_submit'
    end
  end
  # resources :polling_answers

  # dashboard index
  get 'dashboards', to: 'dashboard#index'

  # devise
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # Defines the root path route ("/")
  # root "articles#index"

  # mount action cable
  mount ActionCable.server => '/cable'
end

app/models/qna_room.rb
# frozen_string_literal: true

class QnaRoom < ApplicationRecord
  before_create :generate_code
  after_create_commit { broadcast_prepend_to user_id }

  belongs_to :user
  has_many :qna_questions, dependent: :destroy

  private

  def generate_code
    loop do
      self.code = SecureRandom.alphanumeric(5)
      break unless self.class.exists?(code:)
    end
  end
end

app/controllers/qna_rooms_controller.rb
# frozen_string_literal: true

class QnaRoomsController < ApplicationController
  before_action :authenticate_user!

  layout 'dashboard'

  before_action :set_qna_room, only: %i[show edit update destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :handle_record_not_found

  # GET /qna_rooms
  def index
    @pagy, @qna_rooms = pagy(QnaRoom.where(user_id: current_user.id).order(created_at: :desc))
  end

  # GET /qna_rooms/1
  def show
  end

  # GET /qna_rooms/new
  def new
    @qna_room = QnaRoom.new
  end

  # GET /qna_rooms/1/edit
  def edit
  end

  # POST /qna_rooms
  def create
    @qna_room = QnaRoom.new(qna_room_params)

    if @qna_room.save
      redirect_to @qna_room, notice: 'Qna room was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /qna_rooms/1
  def update
    if @qna_room.update(qna_room_params)
      redirect_to @qna_room, notice: 'Qna room was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /qna_rooms/1
  def destroy
    @qna_room.destroy
    redirect_to qna_rooms_url, notice: 'Qna room was successfully destroyed.', status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_qna_room
    @qna_room = QnaRoom.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def qna_room_params
    params['qna_room']['duration'] = Time.parse(params['qna_room']['duration']).utc unless params['qna_room']['duration'].empty?
    params.require(:qna_room).permit(:title, :description, :duration).merge(user_id: current_user.id)
  end
end

app/views/qna_rooms/_form.html.erb
<%= form_with(model: qna_room, class: "contents") do |form| %>
  <% if qna_room.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(qna_room.errors.count, "error") %> prohibited this qna_room from being saved:</h2>

      <ul>
        <% qna_room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", required: true %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :duration %>
    <%= form.datetime_field :duration, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/qna_rooms/_qna_room.html.erb
<tr>
  <td class="px-4 py-4 text-sm font-medium whitespace-nowrap">
    <div>
      <h2 class="font-medium text-gray-800 dark:text-white "><%= qna_room.title %></h2>
    </div>
  </td>

  <td class="px-4 py-4 text-sm font-medium whitespace-nowrap">
    <div>
      <h2 class="font-medium text-gray-800 dark:text-white "><%= seconds_to_hms(qna_room.duration) %></h2>
    </div>
  </td>
  <td class="px-4 py-4 text-sm whitespace-nowrap">
    <div class="flex items-center gap-x-6">
      <%= button_to qna_room_path(qna_room), method: :get, class: "text-gray-500 transition-colors duration-200 dark:hover:text-yellow-500 dark:text-gray-300 hover:text-yellow-500 focus:outline-none" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
          <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
        </svg>

      <% end %>

      <%= button_to edit_qna_room_path(qna_room), method: :get, class: "text-gray-500 transition-colors duration-200 dark:hover:text-yellow-500 dark:text-gray-300 hover:text-yellow-500 focus:outline-none" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
          <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10"/>
        </svg>
      <% end %>

      <%= button_to qna_room_path(qna_room.id), method: :delete, data: { confirm: 'Are you sure you want to delete this post?' }, class: "text-gray-500 transition-colors duration-200 dark:hover:text-yellow-500 dark:text-gray-300 hover:text-yellow-500 focus:outline-none" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
          <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0"/>
        </svg>
      <% end %>
    </div>
  </td>
</tr>

app/views/qna_rooms/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing qna room</h1>

  <%= render "form", qna_room: @qna_room %>

  <%= link_to "Show this qna room", @qna_room, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to qna rooms", qna_rooms_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/qna_rooms/index.html.erb
<div class="flex justify-between items-center">
  <div>
    <h2 class="text-lg font-medium text-gray-800 dark:text-white">QnA Rooms</h2>
    <p class="mt-1 text-sm text-gray-500 dark:text-gray-300">List QnA Rooms from Milih App</p>
  </div>
  <%= link_to 'New qna room', new_qna_room_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
</div>


<%== render partial: 'layouts/shared/flash_message' %>

<div class="flex flex-col mt-6">
  <% if @qna_rooms.empty? %>
    <%== render partial: 'layouts/shared/empty_section', locals: { domain: 'QnA Rooms' } %>
  <% else %>
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
        <div class="overflow-hidden border border-gray-200 dark:border-gray-700 md:rounded-lg">

          <div class="overflow-auto h-[40rem]">
            <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
              <thead class="bg-gray-50 dark:bg-gray-800 sticky top-0">
              <tr>
                <th scope="col" class="py-3.5 px-4 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">
                  <button class="flex items-center gap-x-3 focus:outline-none">
                    <span>Title</span>

                    <svg class="h-3" viewBox="0 0 10 11" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M2.13347 0.0999756H2.98516L5.01902 4.79058H3.86226L3.45549 3.79907H1.63772L1.24366 4.79058H0.0996094L2.13347 0.0999756ZM2.54025 1.46012L1.96822 2.92196H3.11227L2.54025 1.46012Z" fill="currentColor" stroke="currentColor" stroke-width="0.1"/>
                      <path d="M0.722656 9.60832L3.09974 6.78633H0.811638V5.87109H4.35819V6.78633L2.01925 9.60832H4.43446V10.5617H0.722656V9.60832Z" fill="currentColor" stroke="currentColor" stroke-width="0.1"/>
                      <path d="M8.45558 7.25664V7.40664H8.60558H9.66065C9.72481 7.40664 9.74667 7.42274 9.75141 7.42691C9.75148 7.42808 9.75146 7.42993 9.75116 7.43262C9.75001 7.44265 9.74458 7.46304 9.72525 7.49314C9.72522 7.4932 9.72518 7.49326 9.72514 7.49332L7.86959 10.3529L7.86924 10.3534C7.83227 10.4109 7.79863 10.418 7.78568 10.418C7.77272 10.418 7.73908 10.4109 7.70211 10.3534L7.70177 10.3529L5.84621 7.49332C5.84617 7.49325 5.84612 7.49318 5.84608 7.49311C5.82677 7.46302 5.82135 7.44264 5.8202 7.43262C5.81989 7.42993 5.81987 7.42808 5.81994 7.42691C5.82469 7.42274 5.84655 7.40664 5.91071 7.40664H6.96578H7.11578V7.25664V0.633865C7.11578 0.42434 7.29014 0.249976 7.49967 0.249976H8.07169C8.28121 0.249976 8.45558 0.42434 8.45558 0.633865V7.25664Z" fill="currentColor" stroke="currentColor" stroke-width="0.3"/>
                    </svg>
                  </button>
                </th>

                <th scope="col" class="py-3.5 px-4 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">
                  Duration
                </th>

                <th scope="col" class="relative py-3.5 px-4">
                  <span class="sr-only">Edit</span>
                </th>
              </tr>
              </thead>
              <%= turbo_stream_from current_user.id %>
              <tbody class="bg-white divide-y divide-gray-200 dark:divide-gray-700 dark:bg-gray-900" is="turbo-frame" id="qna_rooms">
              <%= render @qna_rooms %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flex items-center justify-between mt-6">
  <%== render partial: 'layouts/shared/pagy_custom_nav', locals: { pagy: @pagy } %>
</div>

app/views/qna_rooms/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New qna room</h1>

  <%= render "form", qna_room: @qna_room %>

  <%= link_to 'Back to qna rooms', qna_rooms_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/qna_rooms/show.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl"><%= @qna_room.title %> - <%= @qna_room.code %></h1>
    <%= link_to 'Back to QnA Rooms', qna_rooms_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>

  <div class="mt-5 p-4 mb-4 text-sm text-blue-800 rounded-lg bg-blue-50 dark:bg-gray-900 dark:text-blue-400" role="alert">
    <%= @qna_room.description %>
  </div>

  <div id="question" class="overflow-hidden">
    <div class="overflow-y-auto" style="max-height: 72vh;">
    <%= turbo_stream_from @qna_room.id %>
      <ol class="relative border-l border-gray-200 dark:border-gray-700" is="turbo-frame" id="qna_questions" style="overflow-y: auto;">
        <% @qna_room.qna_questions.order(created_at: :desc).each do |qna| %>
          <%== render partial: 'qna_questions/qna_question', locals: { room: @qna_room, qna: qna } %>
        <% end %>
      </ol>
    </div>
  </div>

</div>