config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # qna's
  resources :qna_rooms
  post 'qna_questions/ask_question'
  get 'qna_questions/form'

  # polling's
  resources :pollings do
    collection do
      get 'user/status', to: 'user_polling#redirect_status_page', as: 'user_status'
      get 'user/:code', to: 'user_polling#form', as: 'user_polling'
      post 'user/submit', to: 'user_polling#submit', as: 'user_submit'
    end
  end
  # resources :polling_answers

  # dashboard index
  get 'dashboards', to: 'dashboard#index'

  # devise
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # Defines the root path route ("/")
  # root "articles#index"

  # mount action cable
  mount ActionCable.server => '/cable'
end

app/models/polling.rb
# frozen_string_literal: true

class Polling < ApplicationRecord
  before_create :generate_code
  after_create_commit { broadcast_prepend_to user_id }

  has_many :polling_answers, dependent: :destroy

  private

  def generate_code
    loop do
      self.code = SecureRandom.alphanumeric(5)
      break unless self.class.exists?(code:)
    end
  end
end

app/controllers/pollings_controller.rb
# frozen_string_literal: true

class PollingsController < ApplicationController
  before_action :authenticate_user!

  layout 'dashboard'

  before_action :set_polling, only: %i[show edit update destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :handle_record_not_found

  # GET /pollings or /pollings.json
  def index
    @pagy, @pollings = pagy(Polling.where(user_id: current_user.id).order(created_at: :desc))
  end

  # GET /pollings/1 or /pollings/1.json
  def show
    @polling_answers = @polling.polling_answers
    @total_amount = @polling_answers.pluck(:amount).sum
  end

  # GET /pollings/new
  def new
    @polling = Polling.new
  end

  # GET /pollings/1/edit
  def edit
  end

  # POST /pollings or /pollings.json
  def create
    ActiveRecord::Base.transaction do
      @polling = Polling.create!(polling_params)
      polling_answers = params[:polling_answers].compact_blank.map do |answer|
        { polling_id: @polling.id, description: answer }
      end
      PollingAnswer.insert_all!(polling_answers) # rubocop:disable Rails/SkipsModelValidations
    end
    respond_to do |format|
      format.html { redirect_to polling_url(@polling), notice: 'Polling was successfully created.' }
      format.json { render :show, status: :created, location: @polling }
    end
  rescue ActiveRecord::Rollback => e
    respond_to do |format|
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: e, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /pollings/1 or /pollings/1.json
  def update
    respond_to do |format|
      if @polling.update(polling_params)
        format.html { redirect_to polling_url(@polling), notice: 'Polling was successfully updated.' }
        format.json { render :show, status: :ok, location: @polling }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @polling.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pollings/1 or /pollings/1.json
  def destroy
    @polling.destroy

    respond_to do |format|
      format.html { redirect_to pollings_url, notice: 'Polling was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_polling
    @polling = Polling.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def polling_params
    params['polling']['duration'] = Time.parse(params['polling']['duration']).utc
    params.require(:polling).permit(:title, :duration).merge(user_id: current_user.id)
  end
end

app/views/pollings/_counterwidget.html.erb
<div class="flex justify-between my-3">
  <p id="counter" class="<%= text_size %>"></p>
  <div role="status" id="status">
    <svg aria-hidden="true" class="w-8 h-8 mr-2 text-gray-200 animate-spin dark:text-gray-600 fill-blue-600" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"/>
      <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"/>
    </svg>
    <span class="sr-only">Loading...</span>
  </div>

</div>
<div class="w-full bg-gray-200 rounded-full h-2.5 dark:bg-gray-700">
  <div id="percent" class="bg-red-600 h-2.5 rounded-full"></div>
</div>

<script>
    // Set the date we're counting down to
    var countDownDate = new Date("<%= polling.duration %>").getTime();
    var createdAtDate = countDownDate - (new Date("<%= polling.created_at %>").getTime());
    // Update the count down every 1 second
    var x = setInterval(function () {
        // Get todays date and time
        var now = new Date().getTime();

        // Find the distance between now and the count down date
        var distance = countDownDate - now;

        // Time calculations for days, hours, minutes and seconds
        var days = Math.floor(distance / (1000 * 60 * 60 * 24));
        var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
        var seconds = Math.floor((distance % (1000 * 60)) / 1000);

        // percentage
        var percent = distance / createdAtDate * 100

        // Output the result in an element with id="counter"
        let dom_counter = document.getElementById("counter")
        if (dom_counter) {
            if (days > 0) {
                dom_counter.innerHTML = days + "d " + hours + "h "
                  + minutes + "m " + seconds + "s ";
            } else {
                dom_counter.innerHTML = hours + "h "
                  + minutes + "m " + seconds + "s ";
            }

            document.getElementById("percent").style.width = `${percent}%`

            // If the count down is over, write some text
            if (distance < 0) {
                clearInterval(x);
                dom_counter.innerHTML = "Time is Over";
                document.getElementById("percent").style.width = `0%`
                document.getElementById('status').style.display = 'none'
            }
        }
    }, 1000);
</script>

app/views/pollings/_form.html.erb
<%= form_with(model: polling, remote: true, class: "contents") do |form| %>
  <% if polling.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(polling.errors.count, "error") %> prohibited this polling from being saved:</h2>

      <ul>
        <% polling.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", required: true %>
  </div>

  <div class="my-5">
    <%= form.label :duration %>
    <%= form.datetime_field :duration, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", required: true %>
  </div>

  <div class="my-5">
    <%= form.label :polling_answer, "Polling Answer 1" %>
    <%= form.text_field :polling_answer, name: 'polling_answers[]', class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", required: true %>
  </div>

  <div class="my-5">
    <%= form.label :polling_answer, "Polling Answer 2" %>
    <%= form.text_field :polling_answer, name: 'polling_answers[]', class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", required: true %>
  </div>

  <div class="my-5">
    <%= form.label :polling_answer, "Polling Answer 3 (Optional)" %>
    <%= form.text_field :polling_answer, name: 'polling_answers[]', class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :polling_answer, "Polling Answer 4 (Optional)" %>
    <%= form.text_field :polling_answer, name: 'polling_answers[]', class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>


  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/pollings/_polling.html.erb
<tr>
  <td class="px-4 py-4 text-sm font-medium whitespace-nowrap">
    <div>
      <h2 class="font-medium text-gray-800 dark:text-white "><%= polling.title %></h2>
    </div>
  </td>

  <td class="px-4 py-4 text-sm font-medium whitespace-nowrap">
    <div>
      <h2 class="font-medium text-gray-800 dark:text-white "><%= seconds_to_hms(polling.duration) %></h2>
    </div>
  </td>
  <td class="px-4 py-4 text-sm whitespace-nowrap">
    <div class="flex items-center gap-x-6">
      <%= button_to polling_path(polling), method: :get, class: "text-gray-500 transition-colors duration-200 dark:hover:text-yellow-500 dark:text-gray-300 hover:text-yellow-500 focus:outline-none" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
          <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
        </svg>

    <% end %>

      <%= button_to edit_polling_path(polling), method: :get, class: "text-gray-500 transition-colors duration-200 dark:hover:text-yellow-500 dark:text-gray-300 hover:text-yellow-500 focus:outline-none" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
          <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10"/>
        </svg>
      <% end %>

      <%= button_to polling_path(polling.id), method: :delete, data: { confirm: 'Are you sure you want to delete this post?' }, class: "text-gray-500 transition-colors duration-200 dark:hover:text-yellow-500 dark:text-gray-300 hover:text-yellow-500 focus:outline-none" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
          <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0"/>
        </svg>
      <% end %>
    </div>
  </td>
</tr>

app/views/pollings/_polling_bar.html.erb
<div class="my-5">
  <span id="code" class="bg-blue-100 text-blue-800 text-md text-center font-medium mx-auto px-2.5 py-0.5 rounded dark:bg-blue-900 dark:text-blue-300">Polling <%= index + 1 %></span>
  <h1><%= polling_answer.description %></h1>
  <div class="w-full bg-gray-200 rounded-full dark:bg-gray-700 mt-2">
    <% if total_amount.zero? %>
      <div id="<%= polling_answer.id %>" class="bg-blue-600 text-xs font-medium text-blue-100 text-center p-0.5 leading-none rounded-full" style="width: 0%">0%</div>
    <% else %>
      <div id="<%= polling_answer.id %>" class="bg-blue-600 text-xs font-medium text-blue-100 text-center p-0.5 leading-none rounded-full" style="width: <%= polling_answer.amount * 100 / total_amount %>%"><%= polling_answer.amount * 100 / total_amount %>%</div>
    <% end %>
  </div>
</div>

app/views/pollings/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing polling</h1>

  <%= render "form", polling: @polling %>

  <%= link_to "Show this polling", @polling, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to pollings", pollings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/pollings/index.html.erb
<!--<div class="w-full">-->
  <%# if notice.present? %>
<!--    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%#= notice %></p>-->
  <%# end %>

<!--  <div id="pollings" class="min-w-full">-->
    <%#= render @pollings %>
<!--  </div>-->
<!--</div>-->

<div class="flex justify-between items-center">
  <div>
    <h2 class="text-lg font-medium text-gray-800 dark:text-white">Pollings</h2>
    <p class="mt-1 text-sm text-gray-500 dark:text-gray-300">List pollings from Curhat.in App</p>
  </div>
  <%= link_to 'New polling', new_polling_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
</div>


<%== render partial: 'layouts/shared/flash_message' %>

<div class="flex flex-col mt-6">
  <% if @pollings.empty? %>
    <%== render partial: 'layouts/shared/empty_section', locals: { domain: 'Pollings' } %>
  <% else %>
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
        <div class="overflow-hidden border border-gray-200 dark:border-gray-700 md:rounded-lg">

          <div class="overflow-auto h-[40rem]">
            <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
              <thead class="bg-gray-50 dark:bg-gray-800 sticky top-0">
              <tr>
                <th scope="col" class="py-3.5 px-4 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">
                  <button class="flex items-center gap-x-3 focus:outline-none">
                    <span>Title</span>

                    <svg class="h-3" viewBox="0 0 10 11" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M2.13347 0.0999756H2.98516L5.01902 4.79058H3.86226L3.45549 3.79907H1.63772L1.24366 4.79058H0.0996094L2.13347 0.0999756ZM2.54025 1.46012L1.96822 2.92196H3.11227L2.54025 1.46012Z" fill="currentColor" stroke="currentColor" stroke-width="0.1"/>
                      <path d="M0.722656 9.60832L3.09974 6.78633H0.811638V5.87109H4.35819V6.78633L2.01925 9.60832H4.43446V10.5617H0.722656V9.60832Z" fill="currentColor" stroke="currentColor" stroke-width="0.1"/>
                      <path d="M8.45558 7.25664V7.40664H8.60558H9.66065C9.72481 7.40664 9.74667 7.42274 9.75141 7.42691C9.75148 7.42808 9.75146 7.42993 9.75116 7.43262C9.75001 7.44265 9.74458 7.46304 9.72525 7.49314C9.72522 7.4932 9.72518 7.49326 9.72514 7.49332L7.86959 10.3529L7.86924 10.3534C7.83227 10.4109 7.79863 10.418 7.78568 10.418C7.77272 10.418 7.73908 10.4109 7.70211 10.3534L7.70177 10.3529L5.84621 7.49332C5.84617 7.49325 5.84612 7.49318 5.84608 7.49311C5.82677 7.46302 5.82135 7.44264 5.8202 7.43262C5.81989 7.42993 5.81987 7.42808 5.81994 7.42691C5.82469 7.42274 5.84655 7.40664 5.91071 7.40664H6.96578H7.11578V7.25664V0.633865C7.11578 0.42434 7.29014 0.249976 7.49967 0.249976H8.07169C8.28121 0.249976 8.45558 0.42434 8.45558 0.633865V7.25664Z" fill="currentColor" stroke="currentColor" stroke-width="0.3"/>
                    </svg>
                  </button>
                </th>

                <th scope="col" class="py-3.5 px-4 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">
                  Duration
                </th>

                <th scope="col" class="relative py-3.5 px-4">
                  <span class="sr-only">Edit</span>
                </th>
              </tr>
              </thead>
              <%= turbo_stream_from current_user.id %>
              <tbody class="bg-white divide-y divide-gray-200 dark:divide-gray-700 dark:bg-gray-900" is="turbo-frame" id="pollings">
                <%= render @pollings %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flex items-center justify-between mt-6">
  <%== render partial: 'layouts/shared/pagy_custom_nav', locals: { pagy: @pagy } %>
</div>

app/views/pollings/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New polling</h1>

  <%= render "form", polling: @polling %>

  <%= link_to 'Back to pollings', pollings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/pollings/show.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl"><%= @polling.title %> - <%= @polling.code %></h1>
  <%== render partial: 'counterwidget', locals: { polling: @polling, text_size: 'text-4xl' } %>


  <div class="mt-5 p-4 mb-4 text-sm text-blue-800 rounded-lg bg-blue-50 dark:bg-gray-800 dark:text-blue-400" role="alert">
    <span class="font-medium font-extrabold">INFO!</span> This will be realtime for the result.
  </div>
  <div class="contents" data-controller="pollings" data-polling-id="<%= @polling.id %>">
    <% @polling_answers.each_with_index do |polling_answer, index| %>
      <%== render partial: 'polling_bar', locals: { polling_answer: polling_answer, index: index, total_amount: @total_amount } %>
    <% end %>
  </div>

  <%= link_to 'Back to pollings', pollings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>