config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # qna's
  resources :qna_rooms
  post 'qna_questions/ask_question'
  get 'qna_questions/form'

  # polling's
  resources :pollings do
    collection do
      get 'user/status', to: 'user_polling#redirect_status_page', as: 'user_status'
      get 'user/:code', to: 'user_polling#form', as: 'user_polling'
      post 'user/submit', to: 'user_polling#submit', as: 'user_submit'
    end
  end
  # resources :polling_answers

  # dashboard index
  get 'dashboards', to: 'dashboard#index'

  # devise
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # Defines the root path route ("/")
  # root "articles#index"

  # mount action cable
  mount ActionCable.server => '/cable'
end

app/controllers/user_polling_controller.rb
# frozen_string_literal: true

class UserPollingController < ApplicationController
  def form
    code = params[:code]
    @polling = Polling.find_by(code:)
    # if code.nil? || @polling.nil?
    if code.nil? || @polling.nil? || REDIS_CONN.get("#{request.remote_ip}::#{@polling.id}").eql?('true')
      respond_to do |format|
        format.html { redirect_to user_status_pollings_url, alert: 'Polling not found!' }
      end
    else
      render 'user_polling/form'
    end
  end

  def submit
    answer_id = params['answer']
    polling_answer = PollingAnswer.find_by(id: answer_id)
    # if polling_answer.nil?
    if polling_answer.nil? || !REDIS_CONN.set("#{request.remote_ip}::#{polling_answer.polling_id}", true, nx: true, ex: 1.day)
      respond_to do |format|
        format.html { redirect_to user_status_pollings_url, alert: 'Polling not found!' }
      end
    else
      REDIS_CONN.incr(answer_id)
      if polling_answer.update(amount: REDIS_CONN.get(answer_id))
        polling_id = polling_answer.polling_id
        send_broadcast_action_cable!(polling_id, get_all_amount(polling_id))
        respond_to do |format|
          format.html { redirect_to user_status_pollings_url, notice: 'Thank you for choosing polling.' }
        end
      else
        respond_to do |format|
          format.html { redirect_to user_status_pollings_url, alert: 'Polling not found!' }
        end
      end
    end
  end

  private

  def get_all_amount(polling_id)
    answer_polling_amount = Polling.find(polling_id).polling_answers.pluck(:id).map do |polling_answer_id|
      { polling_answer_id:, amount: REDIS_CONN.get(polling_answer_id).to_i }
    end
    { total: answer_polling_amount.pluck(:amount).sum, data: answer_polling_amount }
  end

  def send_broadcast_action_cable!(polling_id, data)
    ActionCable.server.broadcast("pollings_#{polling_id}", data)
  end
end

app/views/user_polling/form.html.erb
<div class="w-full max-w-xl p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 dark:bg-gray-800 dark:border-gray-700 mx-auto mt-14">
  <h5 class="mb-3 text-base text-center font-semibold text-gray-900 md:text-xl dark:text-white">
    <%= @polling.title %>
  </h5>
  <div id="code" class="bg-blue-100 text-blue-800 text-xl text-center font-medium mx-auto px-2.5 py-0.5 rounded dark:bg-blue-900 dark:text-blue-300"><%= @polling.code %></div>
  <%== render partial: 'pollings/counterwidget', locals: { polling: @polling, text_size: 'text-xl' } %>
  <ul class="my-4 space-y-3">
    <% @polling.polling_answers.each do |polling_answer| %>
      <%= form_tag user_submit_pollings_path, method: :post do %>
        <%= hidden_field_tag :answer, polling_answer.id %>
        <li>
          <button type="submit" class="flex items-center p-3 text-base font-bold text-gray-900 rounded-lg bg-gray-50 hover:bg-gray-100 group hover:shadow dark:bg-gray-600 dark:hover:bg-gray-500 dark:text-white">
            <svg fill="none" class="h-6" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M12.75 15l3-3m0 0l-3-3m3 3h-7.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
            </svg>
            <span class="flex-1 ml-3 whitespace-nowrap"><%= polling_answer.description %></span>
            <span class="inline-flex items-center justify-center px-2 py-0.5 ml-3 text-xs font-medium text-gray-500 bg-gray-200 rounded dark:bg-gray-700 dark:text-gray-400">Choose</span>
          </button>
        </li>
      <% end %>
    <% end %>
  </ul>
  <div>
    <a href="#" class="inline-flex items-center text-xs font-normal text-gray-500 hover:underline dark:text-gray-400">
      <svg class="w-3 h-3 mr-2" aria-hidden="true" focusable="false" data-prefix="far" data-icon="question-circle" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M256 8C119.043 8 8 119.083 8 256c0 136.997 111.043 248 248 248s248-111.003 248-248C504 119.083 392.957 8 256 8zm0 448c-110.532 0-200-89.431-200-200 0-110.495 89.472-200 200-200 110.491 0 200 89.471 200 200 0 110.53-89.431 200-200 200zm107.244-255.2c0 67.052-72.421 68.084-72.421 92.863V300c0 6.627-5.373 12-12 12h-45.647c-6.627 0-12-5.373-12-12v-8.659c0-35.745 27.1-50.034 47.579-61.516 17.561-9.845 28.324-16.541 28.324-29.579 0-17.246-21.999-28.693-39.784-28.693-23.189 0-33.894 10.977-48.942 29.969-4.057 5.12-11.46 6.071-16.666 2.124l-27.824-21.098c-5.107-3.872-6.251-11.066-2.644-16.363C184.846 131.491 214.94 112 261.794 112c49.071 0 101.45 38.304 101.45 88.8zM298 368c0 23.159-18.841 42-42 42s-42-18.841-42-42 18.841-42 42-42 42 18.841 42 42z"></path></svg>
        <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 5.25a3 3 0 013 3m3 0a6 6 0 01-7.029 5.912c-.563-.097-1.159.026-1.563.43L10.5 17.25H8.25v2.25H6v2.25H2.25v-2.818c0-.597.237-1.17.659-1.591l6.499-6.499c.404-.404.527-1 .43-1.563A6 6 0 1121.75 8.25z"></path>
      </svg>
      choose polling above !</a>
  </div>
</div>

app/views/user_polling/status.html.erb
<% if notice.present? %>
  <%== render partial: 'user_polling/status/success', locals: { message: notice } %>
<% elsif alert.present? %>
  <%== render partial: 'user_polling/status/not_found', locals: { message: alert } %>
<% else %>
  <%== render partial: 'user_polling/status/not_found', locals: { message: "Page not found!" } %>
<% end %>